#include "i18n.h"
#include "version.h"
static const char *const text[LANG_COUNT][T_COUNT]={
[LANG_EN]={"Language","Classic","Strikes","Time Attack","Mode","Start","Help","About","Quit","New","Hint","Notes (N)","Verify","Theme","Menu","Palette","Back","You Win","You Lose","Next","Retry","Cancel","Change","Wrong","Illegal","Hint used","Notes ON","Notes OFF","Strict","Free","No conflicts","Conflicts: %d","Progress %d%%   Errors %d","Errors","Time","Target","Strikes left","New game","Start a new game? Current progress will be lost.","Change mode","Change mode to %s?\nThis will start a new game.","Could not find a usable TTF/OTF font.\nInstall a TrueType/OpenType font or use --font /path/to/font.ttf.","TTF_OpenFont failed with the chosen font.","Goal: fill the 9x9 grid with 1..9 without repeats in rows, columns or boxes.\nModes: Classic; Strikes (3 errors); Time Attack (10 minutes).\nMouse or arrows/WASD select. 1..9 places. N or Shift adds notes.\nH hint; M strict/free; T theme; P pause; ESC returns.",SUDOKURA_NAME_VERSION " — compact Sudoku in C + SDL2.\nAuthor: santirodriguez — https://santiagorodriguez.com\nGPLv3. Press ESC or Back to return.","Continue","Daily Puzzle","Resume","Paused","Restart","Restart this puzzle? Numbers, notes and hints from this attempt will be cleared."},
[LANG_ES]={"Idioma","Clásico","Errores","Contrarreloj","Modo","Jugar","Ayuda","Acerca de","Salir","Nuevo","Pista","Notas (N)","Verificar","Tema","Menú","Números","Volver","Ganaste","Perdiste","Siguiente","Reintentar","Cancelar","Cambiar","Incorrecto","No permitido","Pista usada","Notas activadas","Notas desactivadas","Estricto","Libre","Sin conflictos","Conflictos: %d","Progreso %d%%   Errores %d","Errores","Tiempo","Restante","Errores disponibles","Partida nueva","¿Empezar una partida nueva? Se perderá el progreso actual.","Cambiar modo","¿Cambiar el modo a %s?\nSe iniciará una partida nueva.","No se encontró una fuente TTF/OTF utilizable.\nInstalá una fuente o usá --font /ruta/fuente.ttf.","No se pudo abrir la fuente elegida.","Objetivo: completá la grilla 9x9 con 1..9 sin repetir en filas, columnas ni cajas.\nModos: Clásico; Errores (3 intentos); Contrarreloj (10 minutos).\nEl mouse o las flechas/WASD seleccionan. 1..9 coloca. N o Mayús agrega notas.\nH da una pista; M cambia estricto/libre; T el tema; P pausa; ESC vuelve.",SUDOKURA_NAME_VERSION " — sudoku compacto en C + SDL2.\nAutor: santirodriguez — https://santiagorodriguez.com\nGPLv3. Presioná ESC o Volver para regresar.","Continuar","Sudoku diario","Reanudar","En pausa","Reiniciar","¿Reiniciar este sudoku? Se borrarán los números, notas y pistas de esta partida."},
[LANG_CA]={"Llengua","Clàssic","Errors","Contrarellotge","Mode","Comença","Ajuda","Quant a","Surt","Nova","Pista","Notes (N)","Verifica","Tema","Menú","Números","Enrere","Has guanyat","Has perdut","Següent","Torna-ho a provar","Cancel·la","Canvia","Incorrecte","No permès","Pista utilitzada","Notes activades","Notes desactivades","Estricte","Lliure","Sense conflictes","Conflictes: %d","Progrés %d%%   Errors %d","Errors","Temps","Restant","Errors disponibles","Partida nova","Vols començar una partida nova? Es perdrà el progrés actual.","Canvia el mode","Vols canviar el mode a %s?\nComençarà una partida nova.","No s'ha trobat cap lletra TTF/OTF utilitzable.\nInstal·la'n una o usa --font /camí/lletra.ttf.","No s'ha pogut obrir la lletra triada.","Objectiu: omple la graella 9x9 amb 1..9 sense repeticions a files, columnes ni blocs.\nModes: Clàssic; Errors (3 intents); Contrarellotge (10 minuts).\nEl ratolí o les fletxes/WASD seleccionen. 1..9 col·loca. N o Majús afegeix notes.\nH dona una pista; M canvia estricte/lliure; T el tema; P pausa; ESC torna.",SUDOKURA_NAME_VERSION " — sudoku compacte en C + SDL2.\nAutor: santirodriguez — https://santiagorodriguez.com\nGPLv3. Prem ESC o Enrere per tornar.","Continua","Sudoku diari","Reprèn","En pausa","Reinicia","Vols reiniciar aquest sudoku? S'esborraran els números, les notes i les pistes d'aquesta partida."}}
;
const char*tr(Language l,TextKey k){if(l<0||l>=LANG_COUNT)l=LANG_EN;if(k<0||k>=T_COUNT)return "";return text[l][k];}
const char*language_name(Language l){static const char*n[]={"English","Español","Català"};return n[l>=0&&l<LANG_COUNT?l:0];}
