#ifndef SUDOKURA_VERSION_H
#define SUDOKURA_VERSION_H

#define SUDOKURA_VERSION_MAJOR 1
#define SUDOKURA_VERSION_MINOR 3
#define SUDOKURA_VERSION_PATCH 5

#define SUDOKURA_STRINGIFY_INNER(value) #value
#define SUDOKURA_STRINGIFY(value) SUDOKURA_STRINGIFY_INNER(value)
#define SUDOKURA_VERSION \
  SUDOKURA_STRINGIFY(SUDOKURA_VERSION_MAJOR) "." \
  SUDOKURA_STRINGIFY(SUDOKURA_VERSION_MINOR) "." \
  SUDOKURA_STRINGIFY(SUDOKURA_VERSION_PATCH)
#define SUDOKURA_NAME_VERSION "Sudokura v" SUDOKURA_VERSION

#endif
