name: Build Sudokura v1
on:
  workflow_dispatch:
  push:
    tags:
      - 'v1.*'

jobs:
  linux-appimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y \
            libsdl2-dev libsdl2-ttf-dev pkg-config wget imagemagick fuse

      - name: Build linux binary
        run: |
          set -euo pipefail
          gcc -std=c11 -O2 -Wall -Wextra sudokura_sdl.c -o Sudokura-v1 \
            $(pkg-config --cflags --libs sdl2 SDL2_ttf) -lm

      - name: Prepare AppDir (+ desktop + icon)
        run: |
          set -euo pipefail
          mkdir -p AppDir/usr/bin
          cp Sudokura-v1 AppDir/usr/bin/
          chmod +x AppDir/usr/bin/Sudokura-v1

          cat > AppDir/sudokura.desktop <<'EOF'
          [Desktop Entry]
          Type=Application
          Name=Sudokura v1
          Exec=Sudokura-v1
          Icon=sudokura
          Categories=Game;
          EOF

          convert -size 256x256 xc:'#3B4A7A' AppDir/sudokura.png

      - name: Deploy runtime to AppDir (linuxdeploy)
        run: |
          set -euo pipefail
          wget -O linuxdeploy.AppImage \
            https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy.AppImage

          ./linuxdeploy.AppImage --appdir AppDir \
            --executable AppDir/usr/bin/Sudokura-v1 \
            --desktop-file AppDir/sudokura.desktop \
            --icon-file AppDir/sudokura.png

      - name: Create AppImage (appimagetool)
        run: |
          set -euo pipefail
          wget -O appimagetool.AppImage \
            https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool.AppImage
          ARCH=x86_64 ./appimagetool.AppImage AppDir Sudokura-v1-x86_64.AppImage
          ls -lh Sudokura-v1-x86_64.AppImage
          file Sudokura-v1-x86_64.AppImage

      - uses: actions/upload-artifact@v4
        with:
          name: Sudokura-v1-x86_64.AppImage
          path: Sudokura-v1-x86_64.AppImage

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: brew install sdl2 sdl2_ttf pkg-config
      - name: Build (and add fallback font)
        run: |
          set -euo pipefail
          clang -std=c11 -O2 -Wall -Wextra sudokura_sdl.c -o Sudokura-v1 \
            $(pkg-config --cflags --libs sdl2 SDL2_ttf) -lm
          mkdir -p mac-dist/fonts
          curl -L -o mac-dist/fonts/NotoSans-Regular.ttf \
            https://github.com/google/fonts/raw/main/ofl/notosans/static/NotoSans-Regular.ttf
          cp Sudokura-v1 mac-dist/
          (cd mac-dist && zip -9r ../Sudokura-v1-macos.zip .)
      - uses: actions/upload-artifact@v4
        with:
          name: Sudokura-v1-macos.zip
          path: Sudokura-v1-macos.zip

  windows-msys2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_ttf
            zip

      - name: Build EXE
        shell: msys2 {0}
        run: |
          set -euo pipefail
          gcc -std=c11 -O2 -s -Wall -Wextra sudokura_sdl.c -o Sudokura-v1.exe \
            $(pkg-config --cflags --libs sdl2 SDL2_ttf) -lm

      - name: Stage runtime (DLLs + font) into dist/
        shell: msys2 {0}
        run: |
          set -euo pipefail
          mkdir -p dist/fonts
          cp Sudokura-v1.exe dist/

          # Fuente libre (OFL) para asegurar TTF disponible
          curl -L -o dist/fonts/NotoSans-Regular.ttf \
            https://github.com/google/fonts/raw/main/ofl/notosans/static/NotoSans-Regular.ttf

          # DLLs mínimas habituales para SDL2/SDL2_ttf en MSYS2
          for f in \
            /mingw64/bin/SDL2.dll \
            /mingw64/bin/SDL2_ttf.dll \
            /mingw64/bin/libfreetype-6.dll \
            /mingw64/bin/libharfbuzz-0.dll \
            /mingw64/bin/libgraphite2.dll \
            /mingw64/bin/libbz2-1.dll \
            /mingw64/bin/libbrotlidec.dll \
            /mingw64/bin/libbrotlicommon.dll \
            /mingw64/bin/libpng16-16.dll \
            /mingw64/bin/zlib1.dll \
            /mingw64/bin/libglib-2.0-0.dll \
            /mingw64/bin/libiconv-2.dll \
            /mingw64/bin/libintl-8.dll \
            /mingw64/bin/libpcre2-8-0.dll \
            /mingw64/bin/libgcc_s_seh-1.dll \
            /mingw64/bin/libwinpthread-1.dll \
          ; do
            [ -f "$f" ] && cp -n "$f" dist/ || true
          done

          # Reducir tamaño
          strip --strip-unneeded dist/*.dll || true
          strip --strip-unneeded dist/*.exe || true

          echo "Final contents of dist/:"
          ls -lh dist

      # Sube la carpeta (GitHub la comprimirá UNA sola vez al descargar)
      - uses: actions/upload-artifact@v4
        with:
          name: Sudokura-v1-windows
          path: dist
